/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/app-header.vue')['default']
    AuthOverlay: typeof import('./src/components/auth-overlay.vue')['default']
    LottieAnimation: typeof import('vue3-lottie')['Vue3Lottie']
    LoveHowLong: typeof import('./src/components/love-how-long.vue')['default']
    LoveLetterEmpty: typeof import('./src/components/love-letters/love-letter-empty.vue')['default']
    LoveLetters: typeof import('./src/components/love-letters/index.vue')['default']
    NavigationFooter: typeof import('./src/components/navigation-footer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarAppBar: typeof import('@varlet/ui')['_AppBarComponent']
    VarBottomNavigation: typeof import('@varlet/ui')['_BottomNavigationComponent']
    VarBottomNavigationItem: typeof import('@varlet/ui')['_BottomNavigationItemComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarDatePicker: typeof import('@varlet/ui')['_DatePickerComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarOverlay: typeof import('@varlet/ui')['_OverlayComponent']
    VarPopup: typeof import('@varlet/ui')['_PopupComponent']
    VarSkeleton: typeof import('@varlet/ui')['_SkeletonComponent']
    VarSnackbar: typeof import('@varlet/ui')['_SnackbarComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
    VarSwipe: typeof import('@varlet/ui')['_SwipeComponent']
    VarSwipeItem: typeof import('@varlet/ui')['_SwipeItemComponent']
  }
  export interface ComponentCustomProperties {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
